[package]
name = "naf"
version = "0.1.0"
authors = ["Thom Wright <dev@thomwright.co.uk>"]
edition = "2018"

[dependencies]
crossterm = "0.18.2"
tui = { version = "0.12", default-features = false, features = ['crossterm'] }
