name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print version
      run: cargo --version && cargo clippy --version
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- --deny warnings
    - name: Run tests
      run: cargo test --verbose
